[package]
name = "deface"
version = "0.4.0"
authors = ["xTrM_"]

[lib]
crate_type = ["cdylib"]

[dependencies]
jvm-rs = { git = "https://github.com/x4e/jvm-rs/" }

[profile.release]
lto = true
codegen-units = 1
