[package]
name = "patcher"
version = "1.0.0"
authors = ["xTrM_"]

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "0.19.0"

[dependencies.jvmti]
path = "rust-jvmti"
version = "0.4.0"

[profile.release]
lto = "thin"
#strip = "debuginfo"